knife4j:
  enable: true
  openapi:
    title: ${hm.swagger.title:云汇智选接口文档}
    description: ${hm.swagger.description:"云汇智选接口文档"}
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - ${hm.swagger.package:com.hmall}

