server:
  port: 8087

hm:
  db:
    database: hm-promotion

spring:
  application:
    name: promotion-service
  cloud:
    nacos:
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
  profiles:
    active: local
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:192.168.116.130}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:sail}
    password: ${SPRING_RABBITMQ_PASSWORD:123}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/hmall}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2
          max-interval: 10000ms
  datasource:
    url: jdbc:mysql://${hm.db.host:192.168.116.130}:3306/hm-promotion?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw:123}
  output:
    ansi:
      enabled: ALWAYS

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

knife4j:
  enable: true
  openapi:
    title: 促销服务接口文档
    description: "云汇智选促销（优惠券秒杀）接口文档"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.promotion.controller
