server:
  port: 8082
  tomcat:
    threads:
      max: 200
    accept-count: 5
    max-connections: 50
hm:
  cart:
    max-amount: 8
  swagger:
    title: 购物车服务car接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart
    pw: 123

spring:
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true # 开启OKHttp功能