server:
  port: 8082
  tomcat:
    threads:
      max: 200
    accept-count: 5
    max-connections: 50
hm:
  cart:
    max-amount: 8
  swagger:
    title: 购物车服务car接口文档
    package: com.hmall.cart.controller
  db:
    database: hm-cart
    pw: 123

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/${hm.db.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true

feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true # 开启OKHttp功能

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto