USE `hm-user`;

-- 生成1200个用户
-- 密码：123456


INSERT INTO `user` (`username`, `password`, `phone`, `create_time`, `update_time`, `status`, `balance`, `role`)
SELECT
    CONCAT('load', LPAD(t.n, 5, '0')),
    '$2b$10$m6sR0DgYx3zBW7QVsj5TKOBr1nKsNB9hnUj6oDvpJ7IECtp.n.Wn2',
    CONCAT('139', LPAD(1000000 + t.n, 7, '0')),
    NOW(), NOW(), 1, 1600000, 0
FROM (
         SELECT a.n + b.n * 10 + c.n * 100 + d.n * 1000 + 1 AS n
         FROM
             (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) a,
             (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) b,
             (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) c,
             (SELECT 0 n UNION SELECT 1 UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) d
     ) t
WHERE t.n BETWEEN 1 AND 1200;