server:
  port: 8080

#    gateway:
#      routes:
#        - id: cart
#          uri: lb://cart-service
#          predicates:
#            - Path=/carts/**
#
#        - id: item
#          uri: lb://item-service
#          predicates:
#            - Path=/items/**,/search/**
#
#        - id: pay
#          uri: lb://pay-service
#          predicates:
#            - Path=/pay-orders/**
#
#        - id: trade
#          uri: lb://trade-service
#          predicates:
#            - Path=/orders/**
#
#        - id: user
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**,/addresses/**
#      default-filters:
#        - AddRequestHeader=Key,value


hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi

