spring:
  redis:
    host: ${SPRING_REDIS_HOST:${REDIS_HOST:192.168.116.130}}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:123456}
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_SERVER_ADDR:192.168.116.130:8848}
        ip: ${SPRING_CLOUD_NACOS_DISCOVERY_IP:192.168.116.1}