hm:
  db:
    host: 192.168.116.130  # 修改为你自己的虚拟机IP地址
    pw: 123                # 修改为 docker 中的 MySQL 密码
    database: hm-promotion

spring:
  cloud:
    nacos:
      server-addr: 192.168.116.130:8848
  redis:
    host: 192.168.116.130
    port: 6379
    password: 123456
    # password: 123321   # 若 Redis 设置了密码，取消注释并填写
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  rabbitmq:
    host: 192.168.116.130
    port: 5672
    username: sail
    password: 123
    virtual-host: /hmall

